steps:
  - name: docker.io/docker:19.03.8
    args:
      - image
      - build
      - --pull
      - --build-arg
      - MACOS_SDK_VERSION=10.15
      - --build-arg
      - XCODE_VERSION=11.5
      - --build-arg
      - XCODE_PRODUCT_BUILD_VERSION=11N605c
      - --build-arg
      - CMAKE_VERSION=3.17.2
      - --build-arg
      - LLVM_VERSION=10.0.0
      - --build-arg
      - OSXCROSS_COMMIT=master
      - --build-arg
      - LIBTOOL_VERSION=2.4.6_1
      - --tag
      - gcr.io/$PROJECT_ID/xx:$_TAG
      - --tag
      - gcr.io/$PROJECT_ID/xx:latest
      - .

images:
  - gcr.io/$PROJECT_ID/xx:$_TAG
  - gcr.io/$PROJECT_ID/xx:latest

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1800s
