steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/xx/xx:$_TAG
      - --destination=gcr.io/$PROJECT_ID/xx/xx:latest
      - --cache=true
      - --cache-ttl=6h
      - --build-arg
      - MACOS_SDK_VERSION=10.15
      - --build-arg
      - XCODE_VERSION=11.5
      - --build-arg
      - XCODE_PRODUCT_BUILD_VERSION=11N605c
      - --build-arg
      - CMAKE_VERSION_MAJOR=3
      - --build-arg
      - CMAKE_VERSION_MINOR=17
      - --build-arg
      - CMAKE_VERSION_PATCH=2
      - --build-arg
      - LLVM_VERSION=10.0.0
      - --build-arg
      - OSXCROSS_COMMIT=master
      - --build-arg
      - LIBTOOL_VERSION=2.4.6_1

tags: ['xx.xx']

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1800s
