steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/xx/xx:${_XCODE_VERSION}-${_XCODE_PRODUCT_BUILD_VERSION}
      - --cache=true
      - --cache-ttl=6h
      - --cache-repo=gcr.io/$PROJECT_ID/xx/xx/cache
      - --dockerfile=Dockerfile
      - --context=dir:///workspace
      - --reproducible
      - --skip-unused-stages=true
      - --build-arg
      - MACOS_SDK_VERSION=${_MACOS_SDK_VERSION}
      - --build-arg
      - XCODE_VERSION=${_XCODE_VERSION}
      - --build-arg
      - XCODE_PRODUCT_BUILD_VERSION=${_XCODE_PRODUCT_BUILD_VERSION}
      - --build-arg
      - CMAKE_VERSION_MAJOR=${_CMAKE_VERSION_MAJOR}
      - --build-arg
      - CMAKE_VERSION_MINOR=${_CMAKE_VERSION_MINOR}
      - --build-arg
      - CMAKE_VERSION_PATCH=${_CMAKE_VERSION_PATCH}
      - --build-arg
      - LLVM_VERSION=${_LLVM_VERSION}
      - --build-arg
      - OSXCROSS_COMMIT=${_OSXCROSS_COMMIT}
      - --build-arg
      - LIBTOOL_VERSION=${_LIBTOOL_VERSION}

tags: ['xx.xx']

timeout: 1800s  # 30min
